name: Build, Deploy Docker Image CI

# Only deploy when a new tag is pushed
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]
      tags:
        - "v*.*.*"
          
# Must match the project() name in CMakeLists.txt
env:
    APP_NAME: sensornode_rp2040
    
# Allow this workflow to write back to the repository
permissions:
    contents: write
    
# Build binary and send to releases
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        name: Build and deploy
        steps:
        
          - name: Check out this repository
            uses: actions/checkout@v3
            
          - name: Build Docker image
            run: docker build -t sensornode-rp2040-image .
            
          - name: Create Docker container
            run: docker create --name sensornode-rp2040-container sensornode-rp2040-image
            
          - name: Copy out .uf2 file
            run: docker cp sensornode-rp2040-container:/project/build/${APP_NAME}.uf2 ./${APP_NAME}.uf2
            
          - name: Put environment variable into the env context
            run: echo "app_name=$APP_NAME" >> $GITHUB_ENV
            
          - name: Push to release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
                files: ${{ env.app_name }}.uf2
#                body_path: CHANGELOG.md
